apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
  labels:
    run: sample-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: sample-nginx